import {
  LayoutDashboard,
  Compass,
  Sparkles,
  FileText,
  Bookmark,
  Map,
  Wrench,
  GraduationCap,
  Globe2,
  FolderKanban,
  Wallet,
  Briefcase,
  Users,
  Calendar,
  MessageSquare,
  Bell,
  CreditCard,
  BadgeCheck,
  Files,
  Scale,
  LifeBuoy,
  Settings,
  Search,
  FlaskConical,
  Banknote,
  Handshake,
  Cpu,
  UserRound,
  Building2,
  Kanban,
  LineChart,
  ClipboardCheck,
  ShieldAlert,
  ScrollText,
  Ticket,
  BookOpen,
  BarChart3,
  Network,
} from "lucide-react";

export const studentNav = [
  { href: "/student/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { href: "/student/discover", label: "Discover", icon: Compass },
  { href: "/student/matches", label: "Matches", icon: Sparkles },
  { href: "/student/applications", label: "Applications", icon: FileText },
  { href: "/student/saved", label: "Saved", icon: Bookmark },
  { href: "/student/career-roadmap", label: "Career roadmap", icon: Map },
  { href: "/student/skills", label: "Skills", icon: Wrench },
  { href: "/student/courses", label: "Courses", icon: GraduationCap },
  { href: "/student/scholarships", label: "Scholarships", icon: BadgeCheck },
  { href: "/student/abroad", label: "Study abroad", icon: Globe2 },
  { href: "/student/projects", label: "Projects", icon: FolderKanban },
  { href: "/student/funding", label: "Funding", icon: Wallet },
  { href: "/student/freelance", label: "Freelance", icon: Briefcase },
  { href: "/student/mentors", label: "Mentors", icon: Users },
  { href: "/student/calendar", label: "Calendar", icon: Calendar },
  { href: "/student/messages", label: "Messages", icon: MessageSquare },
  { href: "/student/notifications", label: "Notifications", icon: Bell },
  { href: "/student/finance", label: "Finance", icon: CreditCard },
  { href: "/student/opportunity-passport", label: "Opportunity Passport", icon: BadgeCheck },
  { href: "/student/documents", label: "Documents", icon: Files },
  { href: "/student/disputes", label: "Disputes", icon: Scale },
  { href: "/student/support", label: "Support", icon: LifeBuoy },
  { href: "/student/settings", label: "Settings", icon: Settings },
];

export const facultyNav = [
  { href: "/faculty/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { href: "/faculty/opportunities", label: "Opportunities", icon: Search },
  { href: "/faculty/exchange", label: "Exchange", icon: Globe2 },
  { href: "/faculty/research", label: "Research", icon: FlaskConical },
  { href: "/faculty/grants", label: "Grants", icon: Banknote },
  { href: "/faculty/consultancy", label: "Consultancy", icon: Handshake },
  { href: "/faculty/technology-transfer", label: "Technology transfer", icon: Cpu },
  { href: "/faculty/applications", label: "Applications", icon: FileText },
  { href: "/faculty/students", label: "Students", icon: GraduationCap },
  { href: "/faculty/mentoring", label: "Mentoring", icon: Users },
  { href: "/faculty/calendar", label: "Calendar", icon: Calendar },
  { href: "/faculty/messages", label: "Messages", icon: MessageSquare },
  { href: "/faculty/notifications", label: "Notifications", icon: Bell },
  { href: "/faculty/support", label: "Support", icon: LifeBuoy },
  { href: "/faculty/profile", label: "Profile", icon: UserRound },
  { href: "/faculty/settings", label: "Settings", icon: Settings },
];

export const organizationNav = [
  { href: "/organization/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { href: "/organization/profile", label: "Organization profile", icon: Building2 },
  { href: "/organization/opportunities", label: "Opportunities", icon: Briefcase },
  { href: "/organization/candidates", label: "Candidates", icon: Users },
  { href: "/organization/pipeline", label: "Pipeline", icon: Kanban },
  { href: "/organization/interviews", label: "Interviews", icon: Calendar },
  { href: "/organization/offers", label: "Offers", icon: BadgeCheck },
  { href: "/organization/co-funding", label: "Co-funding", icon: Wallet },
  { href: "/organization/courses", label: "Courses", icon: GraduationCap },
  { href: "/organization/projects", label: "Projects", icon: FolderKanban },
  { href: "/organization/partnerships", label: "Partnerships", icon: Handshake },
  { href: "/organization/analytics", label: "Analytics", icon: LineChart },
  { href: "/organization/payments", label: "Payments", icon: CreditCard },
  { href: "/organization/messages", label: "Messages", icon: MessageSquare },
  { href: "/organization/notifications", label: "Notifications", icon: Bell },
  { href: "/organization/disputes", label: "Disputes", icon: Scale },
  { href: "/organization/support", label: "Support", icon: LifeBuoy },
  { href: "/organization/team", label: "Team", icon: Users },
  { href: "/organization/settings", label: "Settings", icon: Settings },
];

export const universityNav = [
  { href: "/university-admin/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { href: "/university-admin/review-queue", label: "Review queue", icon: ClipboardCheck },
  { href: "/university-admin/institution-profile", label: "Institution profile", icon: Building2 },
  { href: "/university-admin/students", label: "Students", icon: GraduationCap },
  { href: "/university-admin/faculty", label: "Faculty", icon: Users },
  { href: "/university-admin/organizations", label: "Organizations", icon: Building2 },
  { href: "/university-admin/opportunities", label: "Opportunities", icon: Briefcase },
  { href: "/university-admin/internships", label: "Internships", icon: BadgeCheck },
  { href: "/university-admin/funding", label: "Funding", icon: Wallet },
  { href: "/university-admin/scholarships", label: "Scholarships", icon: BookOpen },
  { href: "/university-admin/erp-integration", label: "ERP integration", icon: Network },
  { href: "/university-admin/partnerships", label: "Partnerships", icon: Handshake },
  { href: "/university-admin/reports", label: "Reports", icon: BarChart3 },
  { href: "/university-admin/disputes", label: "Disputes", icon: Scale },
  { href: "/university-admin/audit-log", label: "Audit log", icon: ScrollText },
  { href: "/university-admin/messages", label: "Messages", icon: MessageSquare },
  { href: "/university-admin/notifications", label: "Notifications", icon: Bell },
  { href: "/university-admin/support", label: "Support", icon: LifeBuoy },
  { href: "/university-admin/team", label: "Team", icon: Users },
  { href: "/university-admin/settings", label: "Settings", icon: Settings },
];

export const ugcNav = [
  { href: "/ugc/dashboard", label: "National dashboard", icon: LayoutDashboard },
  { href: "/ugc/universities", label: "Universities", icon: GraduationCap },
  { href: "/ugc/organizations", label: "Organizations", icon: Building2 },
  { href: "/ugc/opportunities", label: "Opportunities", icon: Briefcase },
  { href: "/ugc/programmes", label: "Programmes", icon: BookOpen },
  { href: "/ugc/co-funding", label: "Co-funding", icon: Wallet },
  { href: "/ugc/grants", label: "Grants", icon: Banknote },
  { href: "/ugc/disputes", label: "Disputes", icon: Scale },
  { href: "/ugc/risk-and-compliance", label: "Risk & compliance", icon: ShieldAlert },
  { href: "/ugc/helpdesk", label: "Helpdesk overview", icon: LifeBuoy },
  { href: "/ugc/policies", label: "Policies", icon: ScrollText },
  { href: "/ugc/analytics", label: "Analytics", icon: LineChart },
  { href: "/ugc/audit-log", label: "Audit log", icon: ScrollText },
  { href: "/ugc/messages", label: "Messages", icon: MessageSquare },
  { href: "/ugc/notifications", label: "Notifications", icon: Bell },
  { href: "/ugc/team", label: "Team", icon: Users },
  { href: "/ugc/settings", label: "Settings", icon: Settings },
];

export const helpdeskNav = [
  { href: "/helpdesk/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { href: "/helpdesk/tickets", label: "Tickets", icon: Ticket },
  { href: "/helpdesk/knowledge-base", label: "Knowledge base", icon: BookOpen },
  { href: "/helpdesk/reports", label: "Reports", icon: BarChart3 },
  { href: "/helpdesk/notifications", label: "Notifications", icon: Bell },
  { href: "/helpdesk/team", label: "Team", icon: Users },
  { href: "/helpdesk/settings", label: "Settings", icon: Settings },
];

export const researcherNav = [
  { href: "/researcher/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { href: "/researcher/profile", label: "Research profile", icon: UserRound },
  { href: "/researcher/projects", label: "Projects", icon: FolderKanban },
  { href: "/researcher/collaborations", label: "Collaborations", icon: Handshake },
  { href: "/researcher/publications", label: "Publications", icon: BookOpen },
  { href: "/researcher/grants", label: "Grants", icon: Banknote },
  { href: "/researcher/technology-transfer", label: "Technology transfer", icon: Cpu },
  { href: "/researcher/datasets", label: "Datasets", icon: Files },
  { href: "/researcher/opportunities", label: "Opportunities", icon: Search },
  { href: "/researcher/matches", label: "Matches", icon: Sparkles },
  { href: "/researcher/applications", label: "Applications", icon: FileText },
  { href: "/researcher/calendar", label: "Calendar", icon: Calendar },
  { href: "/researcher/messages", label: "Messages", icon: MessageSquare },
  { href: "/researcher/notifications", label: "Notifications", icon: Bell },
  { href: "/researcher/support", label: "Support", icon: LifeBuoy },
  { href: "/researcher/settings", label: "Settings", icon: Settings },
];

export const NAV_BY_ROLE = {
  student: studentNav,
  faculty: facultyNav,
  researcher: researcherNav,
  organization: organizationNav,
  "university-admin": universityNav,
  ugc: ugcNav,
  helpdesk: helpdeskNav,
};
